from enum import IntEnum


class Stage(IntEnum):
    PREFLOP = 0
    FLOP = 1
    TURN = 2
    RIVER = 3


class Action(IntEnum):
    FOLD = 0
    CALL = 1
    RAISE_HALF_POT = 2
    RAISE_POT = 3


NUM_PLAYERS = 2
INITIAL_CHIPS = 1000
SMALL_BLIND = 10
BIG_BLIND = 20

MAX_RAISES_PER_STREET = 3

COMMUNITY_CARDS_BY_STAGE = {
    Stage.PREFLOP: 0,
    Stage.FLOP: 3,
    Stage.TURN: 4,
    Stage.RIVER: 5,
}

HAND_STRENGTH_BUCKETS_RL = 11
HAND_STRENGTH_BUCKETS_SIMPLE = 3
BOARD_STRENGTH_BUCKETS = 5
POT_BUCKETS = 5

POT_BUCKET_BOUNDS = [0, 50, 150, 400, 800]

MONTE_CARLO_SIMULATIONS_DEFAULT = 1000


# Q-Learning
QL_LEARNING_RATE = 0.1
QL_DISCOUNT_FACTOR = 0.95
QL_EPSILON_START = 1.0
QL_EPSILON_MIN = 0.05
QL_EPSILON_DECAY = 0.9995
